### PR TITLE
Chores/setup angular tests foundation #106879454

### PR DESCRIPTION
**Pull request by chrisdolendo**
Jasmine fixtures essentially allow you to generate fixture data from controller specs, by calling the `save_fixture` method in the spec.

### CODE REVIEW

**Comment by menslow** [comment]
I haven't worked with Jasmine yet, so I'll leave if to those who have to review Christine's pull request. I'd love a DAHLAI dev team Jasmine walk through tomorrow if you have time though Christine.

**Comment by chrisdolendo** [comment]
@menslow I think a walkthrough is a great idea -- although it would make sense to do the Jasmine walk through when there is already an actual feature to write a test for. What I can also do is show an example from CCP that is full-cycle -- generating the fixture and running the test.

**Comment by chrisdolendo** [comment]
@kaptron @dstavis @CindyConway 

I understand that Jasmine testing is new to everyone. I want to propose, since this isn't a user facing feature, and just a testing foundation, and won't necessarily 'break' anything, that we merge this, and as soon as there is an Angular test worth writing for a feature that I build it out and present it to everyone.

**Comment by exygy-dev** [comment]
@chrisdolendo I'm down with that plan. It's ok to merge this one without a thumbs-up from the client, too, because it's a chore and not user-facing.

**Comment by dstavis** [comment]
@chrisdolendo  I'm down with that plan. It's ok to merge this one without a thumbs-up from the client, too, because it's a chore and not user-facing.

I notice github says this branch has conflicts that must be resolved, though.

**Comment by chrisdolendo** [comment]
Thanks @dstavis! Just fixed the merge conflicts, it was just at app.json.

Thanks folks. Merging.

**Pull request merged**
