### PR TITLE
Explain 2018 income calculation rules #162877862

### PR DESCRIPTION
**Pull request by jrubenoff**
https://www.pivotaltracker.com/n/projects/1405352/stories/162877862

I utilized Foundation's existing tooltip component to avoid creating a new pattern.

Here's what it looks like on the listings page:

tooltip

@emilyshore: After my last comment in Pivotal, I realized that SMEs approved a version of the content that links to the PDF manual at the end. Ideally, we'd have a page on SFMOHCD.org that explains these income exceptions in a more readable way.

Would you like me to work on writing this page and getting that content approved by SMEs, or does this suffice for now?

### CODE REVIEW

**Comment by emilyshore** [comment]
@jrubenoff I'd prefer it if you could writing this page and getting that content approved by SMEs, (instead of linking to a pdf).

**Comment by akegan** [comment]
@jrubenoff is this still ready for review or is it blocked by your work creating a new page on the sfmohcd website?

**Comment by jrubenoff** [comment]
The latter

**Comment by jrubenoff** [comment]
Opening a new PR to minimize merge conflicts.

**Pull request closed without merging**
