### PR TITLE
Chores/refactor listing controller #152862218

### PR DESCRIPTION
**Pull request by chrisdolendo**
**Object**
The objective of this refactor was to remove the need for a `ListingController` to house all the functions related to listings, and separate the functions out to more digestible pieces.

**Approach**
The approach to this objective was to look at the `listings.html` and `listing.html page` - which is already divided into partials - and convert the partials that use lots of controller functions into components that have their own isolated scope with functions only relevant to them.

**Execution**
The result was ultimately having a parent component `listingContainer` serving as a 'parent controller' with functions used in multiple components of listings/listing that components inherit from.

Using `Component Inheritance` allowed the components to have an isolated scope and still access universal functions.

As a result of the refactor, `ListingController` is not longer used/existing in this PR, and has been replaced by a much more slimmed down `listingContainer.`

There is even more that we can do to take this further, but this is a big leap to the refactoring of listings. 

Outstanding Items that @software-project has picked up:
- Figure out why the heck `adjustCarouselHeight` directive won't play nice with the component. It needs to access a function that was in ListingController.scope but even after moving the directive to the component didn't seem to fix the issue.
- Updating the tests aka getting the ListingController spec and separating it out to respective component tests

Reference for inventory of functions:
https://docs.google.com/document/d/1P45xeaTh3GUMzlRMlU8no_74zEySrxENkIiPM1hpHHY/edit

Edit from CC:

### Making a list here of the updates needed from findings in QA:
- [x] Remove empty controllers from new listing-related components
- [x] Public lottery info missing (related to the `LotteryDate` console error on listing page)
- [x] Application deadline date missing from top right
- [x] Priority Units info missing
- [x] Download Application doesn't work
- [x] All Units Reserved For Seniors. Missing "62+"
- [x] Hero photos different size
- [x] Senior building section missing under "Eligibility"
- [x] Missing call information under leasing agent
- [x] Lottery preference section missing content under "Eligibility"
- [x] Missing senior building callout, reserved for seniors, and orange row formatting in Listing Directory
- [x] Intermittently, everything in listing directory view is showing up as senior building. (Goes away on refresh)
- [ ] Lottery results are broken (only able to reproduce once, seems intermittent)
- [x] In lottery results, the date is missing
- [x] Lottery results: missing listing name
- [x] Table is missing on 450 folsom (Household maximum income table

### Round 2 of testing
- [x] 62+ is still missing from Listing directory view after "Reserved for Seniors"
- [x] Household maximum income table doesn't expand to show all of the rows on the PR (450 folsom is a good example)
- [x] "Lottery Preferences" Copy weirdness (see comments below for details, this might be a bug on full)

### CODE REVIEW

**Comment by akegan** [comment]
@chrisdolendo we should start thinking about what our testing strategy should be for this PR.

Since displaying listings doesn't include much interactivity our e2e tests don't cover it super well, right?

We should start coming up with all of the different types of listings and listing states we want to check.

Here are some initial thoughts

### Listings with variable features
- Listing with units with differing AMIs
- Listing that's reserved for seniors

### Listings with variable status
- Listing with applications open
- Listing with applications closed, waiting for lottery
- Listing with lottery results posted

any other thoughts on what potential risks are?

**Comment by chrisdolendo** [comment]
I updated the description of the PR to describe the approach the refactor. Tried to keep the commits as separate and clean and digestible as possible.

**Comment by akegan** [comment]
@software-project Following up from chris's PR description, you were able to fix the adjustCarouselHeight issue, right?

**Comment by callaghanc** [comment]
@akegan The console error on the listing page that I am looking into is likely related to the lottery info being missing

screen shot 2019-01-14 at 10 58 00 am

**Comment by emilyshore** [comment]
Download Application doesn't work.

**Comment by emilyshore** [comment]
All Units Reserved For Seniors. Missing "62+"


Hero photo different size:


Senior Building section is missing


Missing Call information


Lottery Preferences section has missing content

**Comment by jrubenoff** [comment]
> Hero photo different size

@emilyshore I think this one might just be a fluke around how we calculate the height of the hero image.

Can you reload the listings page in the PR, wait 10 seconds, and confirm the height is still different?

**Comment by emilyshore** [comment]
Senior building: missing Senior Building callout, Reserved for Seniors and orange row formatting


In PR, intermittently everything is showing up as Senior Building. If I refresh then those Senior Building boxes go away. 


Lottery Results are broken

**Comment by emilyshore** [comment]
In lottery results, the date is missing:


Lottery Results: missing listing name


Table Missing on 450 Folsom

**Comment by akegan** [comment]
looks like 62+ is still missing from Listing directory view after "Reserved for Seniors"
image

**Comment by akegan** [comment]
Lottery preferences section still has mismatched content (Full is on right)
image

**Comment by akegan** [comment]
Following up on the "Lottery Preferences" Copy, it looks like we've actually found a bug on full where we're not getting both pieces of content even if we're supposed to.

Here's the code on master
```
p.custom-counter_text ng-if="::!listingHasPreferences()"
  span ng-if="::listingIsFirstComeFirstServe()"
    | There will be no lottery. Applications will be reviewed in the order they are received.
  span ng-if="::!listingIsFirstComeFirstServe()"
    | Preference holders will be given highest ranking in the lottery process.
p.custom-counter_text ng-if="::listingHasPreferences()"
  | Anyone may enter the housing lottery for this listing. If your household has one of the following preferences, you will be considered in the order shown here. Each preference holder will be reviewed in lottery rank order.
```

**Comment by emilyshore** [comment]
**Bugs that I now see are fixed**
- Lottery Results: missing listing name: fixed
- Table Missing on 450 Folsom: fixed
- Download Application doesn't work.: fixed
- All Units Reserved For Seniors. Missing "62+”: fixed
- Hero photo different size: fixed
- Senior Building Section is missing: fixed
- Missing call information: fixed
- Senior building: missing Senior Building callout, Reserved for Seniors and orange row formatting: fixed
- In PR, intermittently everything is showing up as Senior Building. If I refresh then those Senior Building boxes go away: fixed
- Lottery Results are broken. Intermittently fails. Failed for us the first time: fixed
- looks like 62+ is still missing from Listing directory view after "Reserved for Seniors (Andrea found yesterday): fixed


**Items not fixed:** 
- In lottery results, the date is missing: ??
- Lottery preferences section has missing content: not fixed


- (Andrea noticed yesterday) Household maximum income table doesn't expand to show all of the rows on the PR: not fixed

**Comment by akegan** [comment]
I put this on slack already but want to follow up here:
@emilyshore  for "In lottery results, the date is missing: seems to be failing, but in a different way than before" it think it's because you've searched for a lottery number on the left, but not on the right.

**Comment by akegan** [comment]
@emilyshore just checked in with @callaghanc on the lottery preferences content. Based on my testing yesterday it looks like this is a bug on master too where intermittently some of the content doesn't show up due to race conditions of some sort. 

I've made a new story to look into it that we can follow up with after the refactor is merged: https://www.pivotaltracker.com/story/show/163273882

**Comment by exygy-dev** [comment]
for the last item in @emilyshore's latest round of QA, "(Andrea noticed yesterday) Household maximum income table doesn't expand to show all of the rows on the PR: not fixed", i've just pushed a fix that removes a typo that was causing that. @emilyshore will retest and let us know if it looks good! after she gives us the go ahead on that, we can merge this PR!

**Comment by emilyshore** [comment]
@akegan @callaghanc 
Household Maximum Income now expands fully. Pass!

**Pull request merged**
