### PR TITLE
Chores/update asset management #161870868

### PR DESCRIPTION
**Pull request by software-project**
https://www.pivotaltracker.com/story/show/161870868

### CODE REVIEW

**Comment by akegan** [comment]
@software-project can you please update this PR with the latest status of your work?

- What you've accomplished
- What's left to be done
- What your latest blockers were when you stopped working on it.

**Comment by software-project** [comment]
What is done:
- General webpack config
- Added loaders for CSS, HTML, images and JS
- Change way of loading of some assets like CSS and locales.
- Import components (Services, Controllers and Components)
- Change way to load templates

What's missing:
- Better way to load templates/ ng-incudes. Right now most of it is done 'by hand'/ file by file
- some images are missing
- Some components might be still missing (need to be imported)
- Preloading of assets
- Raven and Sentry configs
- Angular-foundation package needs to be updates as it's breaking the build due to missing template

**Comment by akegan** [comment]
ok thank you @software-project!

**Comment by akegan** [comment]
closing this now that we have a status update on it

**Pull request closed without merging**
