### PR TITLE
Fix feature table overlap in spanish #170433148

### PR DESCRIPTION
**Pull request by cpalmatier**
Widened title divs in the Features section on rental and ownership listing details viewsto account for long words in non-English languages, especially Spanish

### CODE REVIEW

**Comment by akegan** [comment]
Heroku is having issues deploying this branch because of a sendgrid error. I'm deploying it to https://dahlia-qa-translations.herokuapp.com/ as a backup while I contact heroku support

**Comment by akegan** [comment]
Same issue I left a comment about on the other PR actually. Rental features table needs to be updated too

See e.g. [Edwin Lee apartments](https://dahlia-qa-translations.herokuapp.com/es/listings/a0W0P00000HbryHUAR)
image

**Comment by akegan** [comment]
Looks good except for as you mentioned from 770-830 px width still has the overlap. Is it worth forcing a wrap for that case?

**Comment by cpalmatier** [comment]
Made a utility class over in pattern-library hanging off https://github.com/Exygy/sf-dahlia-pattern-library/pull/115 to force word wrap, so as soon as that's merged I can fix it over here.

**Comment by cpalmatier** [comment]
Should be good to merge once tests pass.

**Comment by akegan** [comment]
quick update, won't be able to get tests to pass on this until Larry's change is deployed to full so the field is available to update VCRs

**Pull request merged**
