### PR TITLE
Bugs/under six filter #112837033

### PR DESCRIPTION
**Pull request by chrisdolendo**
Bug fix for Eligibility Est form: https://www.pivotaltracker.com/story/show/112837033

I realize that writing unit tests on this actually aren't effective tests to ensure that the bug doesn't happen again. I feel like an end-to-end (E2E) test is more appropriate for it, though I haven't written one for Angular before.

I have a feeling it's worth writing an E2E test for bug specific stories. Might be something worth thinking about later on.

### CODE REVIEW

**Comment by kaptron** [comment]
:+1: verified that it sets children_under_6 to "0" when you uncheck the box.

**Comment by menslow** [comment]
@chrisdolendo I don't see this part of the acceptance criteria reflected in any of these code changes.

## Acceptance:

* Do not pass includeChildrenUnder6 filter to Salesforce.

**Comment by chrisdolendo** [comment]
@menslow Yeah it was already implemented when I pulled from master: https://github.com/Exygy/sf-dahlia-web/blob/bugs/under-six-filter-%23112837033/app/controllers/api/v1/listings_controller.rb 

See `def eligibility`

**Comment by menslow** [comment]
@chrisdolendo Sweet! Thumbs up on this PR then. I'll "accept" the bug too.

**Comment by chrisdolendo** [comment]
Thanks @menslow and @kaptron!

**Pull request merged**
