### PR TITLE
[#136294971] - Bugfix - reassign primary applicant to preference on s…

### PR DESCRIPTION
**Pull request by chrisdolendo**
…ave draft

### CODE REVIEW

**Comment by kaptron** [comment]
@chrisdolendo Looks great -- and also looks like a good example to add a test 😜  -- even just a small unit test that just checks when you run `importUserData` that it has changed the values as expected.

**Comment by chrisdolendo** [comment]
@kaptron ha! you are right. fair enough.

**Comment by chrisdolendo** [comment]
@kaptron just wrote the spec!

**Comment by kaptron** [comment]
great! 👍

**Pull request merged**
