### PR TITLE
[#126801511] - Applicant can review submitted application after submi…

### PR DESCRIPTION
**Pull request by chrisdolendo**
…scion

Link on the confirmation page, accessible whether or not they are signed in

### CODE REVIEW

**Comment by chrisdolendo** [comment]
@kaptron updated the code to what we discussed with Jesse -- have a look see!

**Comment by chrisdolendo** [comment]
@kaptron, this PR says you requested changes but wondering if you can approve so I can squash and merge? just don't wanna diss your request even if you gave the go on slack haha :dancer:

**Comment by kaptron** [comment]
@chrisdolendo I only looked at the code but I'd like to actually click through it in the app as well, will do this afternoon!

**Comment by chrisdolendo** [comment]
@kaptron ok sounds good!

**Comment by kaptron** [comment]
@chrisdolendo approved! 👍  I just added a couple of tweaks to handle the state when you go through that flow as a logged in user, in that case I just have it take you to the `short-form-review` page since it's basically like taking them to My Applications which is their other option from the confirmation page.

**Pull request merged**
