### PR TITLE
Features/Rename pricing table columns #164175404

### PR DESCRIPTION
**Pull request by akegan**
https://www.pivotaltracker.com/story/show/164175404

### CODE REVIEW

**Comment by akegan** [comment]
Still TODO: update language around HOA dues

**Comment by akegan** [comment]
Still TBD: 
what to do about HOA dues language on listing directory page?
What to do about very long column titles on mobile view?

**Comment by akegan** [comment]
# Listing Directory
*Desktop*
image 9
*Mobile*
image 8

# Listing Details
*Desktop*
image 6
*Mobile*
image 7

**Comment by akegan** [comment]
@jrubenoff or @callaghanc this is ready for review

**Comment by callaghanc** [comment]
@akegan i'll do a quick review of the code and leave it to @jrubenoff to add another review on this PR if he wants and also to do the QA on the Pivotal story since it's mainly about content/design

**Pull request merged**
