### PR TITLE
Features/See listings link to home #164022926

### PR DESCRIPTION
**Pull request by akegan**
https://www.pivotaltracker.com/story/show/164022926

### CODE REVIEW

**Comment by akegan** [comment]
@jrubenoff I'm not sure if the styling on these is correct.

My applications was tough because it's pretty narrow 
image

Both of them are lacking padding on mobile
image

image

can you work your css magic to get them to look right?

**Comment by jrubenoff** [comment]
Done! Please test

**Comment by akegan** [comment]
@jrubenoff looks like the gray cuts through the middle of the buttons on mobile view for my favorites
image

for my applications, it looks good on mobile, but the buttons are stacked on desktop
image
is that expected?

**Comment by jrubenoff** [comment]
Thanks! Should be fixed.

Both should look stacked on desktop, like this:

screen shot 2019-02-19 at 5 34 53 pm

**Comment by akegan** [comment]
ok looks good. ready for review from another eng!

**Comment by akegan** [comment]
@jrubenoff looks like your changes to fix that may have still not made it onto the PR. can you push again?

**Comment by jrubenoff** [comment]
Done!

On Feb 20, 2019, at 2:04 PM, Andrea Egan <notifications@github.com<mailto:notifications@github.com>> wrote:


This message is from outside the City email system. Do not open links or attachments from untrusted sources.



@jrubenoff<https://github.com/jrubenoff> looks like your changes to fix that may have still not made it onto the PR. can you push again?

**Comment by akegan** [comment]
looks good now. I'll merge once tests pass

**Pull request merged**
