### PR TITLE
Features/ownership-pricing-tables #162561704

### PR DESCRIPTION
**Pull request by akegan**
https://www.pivotaltracker.com/story/show/162561704

### CODE REVIEW

**Comment by akegan** [comment]
alright. very-garbage-looking table pushed for ownership property cards too.

image
@jrubenoff  and I are going to go over this today to start to come up with a plan, but it's up for checking out as is for now

**Comment by jrubenoff** [comment]
This seems fine to me for now, if someone would like to code review it.

**Comment by akegan** [comment]
@callaghanc are you up for giving this a code review if you have time before you head offline tomorrow?

**Comment by callaghanc** [comment]
@akegan I may not have time before end of today, but if I do I will take a look

**Comment by akegan** [comment]
just renamed files and variable to sale instead of ownership

**Comment by akegan** [comment]
looks like I have to update some tests on this so I'm going to leave the WIP label on there

**Comment by akegan** [comment]
@jrubenoff heads up a shifted the property card stats to partials instead of components. should just be a filename change for you

**Comment by akegan** [comment]
@callaghanc this is ready for review now

**Comment by callaghanc** [comment]
@akegan i've had the rest of my day consumed by meetings, so will review this either tonight or over the weekend

**Comment by akegan** [comment]
@callaghanc I've renamed the files, ready for review again

**Comment by callaghanc** [comment]
@akegan cool will approve when tests pass!

**Pull request merged**
