### PR TITLE
Chore/update angular version 139599023

### PR DESCRIPTION
**Pull request by LoganArnett**
This PR Covers [ticket #139599023](https://www.pivotaltracker.com/story/show/139599023)

### CODE REVIEW

**Comment by akegan** [comment]
@LoganArnett if it's not too traumatic to relive the struggle of this ticket, would you be up for summarizing the changes you had to make and why for a bit of context?

**Comment by akegan** [comment]
@LoganArnett looks like deploy is failing due to:
`ExecJS::RuntimeError: SyntaxError: Unexpected token operator «=», expected punc «,»` in rake assets:precompile. This is a different error than the one I just fixed so I think it might be related to your changes?

**Comment by akegan** [comment]
jasmine tests are failing for me both locally and on semaphore. @LoganArnett I'd like to check in with you again on this PR to understand where you were at with this better.

**Comment by LoganArnett** [comment]
## Current Condition
What is done:
  * Angular and all other bower dependencies exist in package.json
  * Main application is functional 
  * Jasmine tests and e2e are updated for the main Angular breaking changes

What is still an issue:
  * Jasmine and e2e tests are not consistent across environments and even users
  * Deployment on Heroku is broken on build due to dependencies with ES6 syntax on build
  * Certain inconsistencies in Services and passing of state appear to be the main issue on testing

**Pull request closed without merging**
