### PR TITLE
Features/full/prod disable features temp #150937154

### PR DESCRIPTION
**Pull request by chrisdolendo**
opening this version as well - branched from prod, PR-ed to prod

### CODE REVIEW

**Comment by chrisdolendo** [comment]
I notice that this breaks a bunch of E2E tests as a result. My commits are most patterns, should I just  comment the breaking tests or let them fail? :thinking:

**Comment by kaptron** [comment]
@chrisdolendo no need to change the tests around, you can let them fail 😈  
I think they're actually only failing because `production` and Salesforce Full don't play together nicely, Full is setup for multifamily, but `production` is not yet. So nothing to do w/ your code.

plus since this is going to get reverted anyway, no need to worry about it. 

lastly I believe your Q about the background, this is the same thing that gets fixed in #857. We didn't schedule that in the release -- but not a big deal, just a minor visual thing.

**Comment by kaptron** [comment]
👍  looks good to me. 

also it was nice of you to leave all the notes of where to revert stuff, but we can literally just `git revert` this whole change, so no biggie either way. 😸

**Comment by chrisdolendo** [comment]
true!

**Comment by creativecoder** [comment]
👍

Just a reminder: you don't need to specify `/full/` anymore. Everything defaults testing on full unless there is `/qa/` in the branch name, then it will test on QA.

Let's think about what (if any) part of this functionality should live behind a feature flag in the future. I can imagine us wanting to do a similar thing again the next time we freeze caching for a joint Salesforce/web app deploy. (I'll make a pivotal story.)

**Comment by kaptron** [comment]
good point re: feature flags. This use case was pretty specific though, in that pref refactor specifically had breaking changes e.g. with viewing your past applications and past lottery results, so I'd be wary of leaving too much of this in there with conditionals (i.e. _over_-configuring things). 

That being said, the nicely disabled sign in page seems like a good potential one to feature flag.

**Comment by chrisdolendo** [comment]
:+1: thanks for the reviews!

Msol just accepted this so it's ready to go whenever.

**Comment by kaptron** [comment]
@chrisdolendo you can go ahead and merge this! that will auto-deploy it to `dahlia-pre-prod` and then later after 5pm we will push it live.

**Comment by kaptron** [comment]
@chrisdolendo it was getting to be time, so I merged it.... can't say I didn't give you the chance to press the button :grin:

bitmoji

**Pull request merged**
