### PR TITLE
Chores/use instantiated objects #152047375

### PR DESCRIPTION
**Pull request by callaghanc**

### CODE REVIEW

**Comment by chrisdolendo** [comment]
@callaghanc can you remind me where we left this off? Did you create a chore to write tests or were you gonna do them here? The chore is still in flight and I :+1: the code, so we can merge it when checks pass and there are no conflicts :)

**Comment by creativecoder** [comment]
I believe this was just waiting for engineering review.

**Comment by callaghanc** [comment]
@chrisdolendo @creativecoder Chris is correct about where we left this one, we decided to create this separate chore for writing tests to reach a coverage level that Code Climate is happy with: https://www.pivotaltracker.com/story/show/153680720. So this just needs an engineering review and needs the tests to pass, and then we can merge it, ignoring the Code Climate total coverage red mark.

**Comment by creativecoder** [comment]
Note to resolve changes in `listing_controller.rb` https://github.com/Exygy/sf-dahlia-web/pull/895/files when that PR is merged from master into this branch.

**Comment by chrisdolendo** [comment]
Grant will write tests by end of week with his additional refactor

**Comment by creativecoder** [comment]
I think this one is finally ready. @callaghanc Please take another look when you get back Tue to make sure you're happy with where I ended up in the `Force::Request` class. But I'm going to merge so this can be part of release testing.

**Pull request merged**
