### PR TITLE
Features/full/master multilingual #148422881

### PR DESCRIPTION
**Pull request by kaptron**
This is the `multilingual + master` branch -- it's somewhat of a frankenstein simply because it basically:
 - pulled in `multilingual`
 - pulled in _some_ stuff from `multifamily` that was setup for multilingual
 - undid the stuff from both of those that was multifamily-specific (senior building, community building eligibility, etc)

Engineering note to be prepared when this goes live + ready to merge upstream to MF + ML, that we'll want to handle that in a particular way:
 1. Make sure `multifamily` is totally up-to-date with master prior to this branch getting merged
 1. This branch gets merged/deployed (Multilingual release)
 1. Merge the "original" `multilingual` branch into `multifamily`
 1. Merge `master` into `multifamily` (which is now MF + ML) 
 1. Get a bunch of conflicts... ignore them (`git checkout --ours` from `multifamily`) since we want to keep the original branch and not this frankenstein one.

### CODE REVIEW

**Comment by kaptron** [comment]
huzzah ✅

**Comment by chrisdolendo** [comment]
Wow! This is a ginormous merge. I applaud. Did e2e tests help you in making sure nothing fell through the cracks?

**Comment by kaptron** [comment]
@chrisdolendo definitely!

**Comment by kaptron** [comment]
closing this PR... we're not going to release `multilingual` pre multifamily any more

**Pull request closed without merging**
