### PR TITLE
Features/update confirmation email #146896023

### PR DESCRIPTION
**Pull request by chrisdolendo**

### CODE REVIEW

**Comment by kaptron** [comment]
@chrisdolendo can you rename + label the PR according to the way I pointed out yesterday? thanks!

**Comment by chrisdolendo** [comment]
@kaptron ah yes! thank you for the reminder.

**Comment by kaptron** [comment]
@chrisdolendo please use same format as other PR names (can refer to any of the others --
 capitalized, without dashes), and add the PR label `master` (obviously I could do all this, but want you to get in the good habit)

**Comment by chrisdolendo** [comment]
@kaptron third time's the charm :p

**Comment by kaptron** [comment]
@chrisdolendo still no label tho... 
bitmoji

**Comment by chrisdolendo** [comment]
@kaptron 

/bitmoji for shame

**Pull request merged**
