### PR TITLE
Fix chinese salutation interpolation issue #170408210

### PR DESCRIPTION
**Pull request by akegan**
Found while release testing. https://www.pivotaltracker.com/story/show/170408210

### CODE REVIEW

**Comment by akegan** [comment]
@sashax are you up for reviewing this PR?

**Comment by sashax** [comment]
Looks like there are a number of other variables that are mis-cased. See, eg., lines 886 and 891.

**Comment by akegan** [comment]
@sashax pushed changes for the other variables that started with capital letters, and and an issue with tagalog where translator added a space between the words.

Checked for both of these patterns with a regex search in all the languages and didn't see any more of them

**Comment by sashax** [comment]
lgtm. 👍

**Pull request merged**
