### PR TITLE
Feaures/only display rental listing #162561695

### PR DESCRIPTION
**Pull request by software-project**
https://www.pivotaltracker.com/story/show/162561695

### CODE REVIEW

**Comment by callaghanc** [comment]
@software-project Could you update the review instructions on the related Pivotal story for this with a link to the review app and slightly more detailed instructions?

**Comment by software-project** [comment]
@callaghanc  I think the issue with heroku continues. I clicked 'Retry' but it failed.

**Comment by callaghanc** [comment]
@software-project yes, we're still working with Heroku on the account billing issues which are affecting deployment

**Comment by callaghanc** [comment]
Closing to re-open a new PR with correct spelling of "features" in the branch name.

**Pull request closed without merging**
