### PR TITLE
Bugs/email validation #151134233

### PR DESCRIPTION
**Pull request by callaghanc**

### CODE REVIEW

**Comment by creativecoder** [comment]
@callaghanc Please update PR name using our standard format

**Comment by callaghanc** [comment]
@creativecoder I'll look into block regular expressions and add the reference. If you check out the engineering notes on the Pivotal story, there's an explanation of why I'm using that regex.

**Comment by callaghanc** [comment]
Oh didn't know about the CoffeeScript multiline regexes, good to know, thanks! Added e2e test. Also added regex validation to more email fields.

**Comment by kaptron** [comment]
looks like everything @creativecoder requested is in there now 👍  story has been approved and product team wants in the release -- will check in at standup otherwise this should be ready to merge.

**Pull request merged**
