### PR TITLE
Update pre-requisites page content #164418056

### PR DESCRIPTION
**Pull request by akegan**
https://www.pivotaltracker.com/story/show/164418056

What it looks like now: 
image

### CODE REVIEW

**Comment by akegan** [comment]
pretty much done, just waiting for confirmation that styling looks ok from @jrubenoff

**Comment by callaghanc** [comment]
@akegan @jrubenoff i know this story is about text content, but i noticed that there's very little spacing after the file uploader on the prerequisites page and it looks kind of cramped. screenshots to compare to how much spacing is after the file uploader on the rent burdened page. could we add a little more spacing below the file uploader on the prerequisites page in this PR?
Screen Shot 2019-03-26 at 1 52 46 PM
Screen Shot 2019-03-26 at 1 52 00 PM

**Comment by jrubenoff** [comment]
@callaghanc Sure, want to add the `margin-bottom--2x` class?

**Comment by akegan** [comment]
look better @callaghanc and @jrubenoff ? 
image

**Pull request merged**
