### PR TITLE
Remove stale hardcoded features #163463841

### PR DESCRIPTION
**Pull request by chrisdolendo**
https://www.pivotaltracker.com/story/show/163463841

Summary of Code Removed:
1. Removed slug capabilities (creating a semantic url for certain listings e.g. `/listings/480potrero`), acc to SME, there is no plan to maintain this. Slugs were removed for the following:

- 480 Potrero	
- Alchemy	
- 21 Clarence	
- 168 Hyde	
- Olume	
- Rincon	
- Potrero 1010	
- 529 Stevenson	
- 888 Paris	
- 77 Bluxome	
- 3445 Geary	
- 125 Mason	
- Argenta 909	
- Northpoint Vistas	
- 280 Brighton	
- 30 Dore	
- 168 Hyde Relisting	
- L Seven	
- Test Listing	
- AMI Chart Test 477	
- Abaca	
- Transbay Block 7
- 750 Harrison Street

2. Removed any hardcoded references in the listings pages for the following due to being inactive:
- 750 Harrison Street 
- 168 Hyde Relisting
- Transbay Block 7

3. Removed stubbing of listing preferences for old listings including Alchemy, 480 Potrero, 21 Clarence, 168 Hyde, Olume, 3445 Gear, 125 Mason, Argenta 909, Northpoint Vistas, 280 Brighton, and 30 Dore, since they are either no longer active or the data is returned from salesforce

Notes: 
- Code related to 1335 Folsom and Merry Go Round is kept because building still has available units acc to SME
- Still kept hardcode on customproofpreferences  because this story is still not implemented: https://www.pivotaltracker.com/story/show/154784101

### CODE REVIEW

**Comment by akegan** [comment]
@chrisdolendo I checked in with Emily a bit on this. Is it feasible to translate what we've removed into a doc to make it a bit clearer what we're deleting? That way we can share it with SMEs and also have a record of it for ourselves.

**Comment by chrisdolendo** [comment]
@akegan done -- see description. Let me know if you want something more specific.

**Comment by akegan** [comment]
@chrisdolendo were you able to test these changes locally? deploy failed due to asset compiling and all tests failed too. I wonder if there's a syntax error hiding somewhere

**Comment by chrisdolendo** [comment]
@akegan the deploying is fixed so this is ready for review 👍

**Pull request merged**
