### PR TITLE
[#141224273] Adds "Find out more" link to COP/DTHP preference descriptions

### PR DESCRIPTION
**Pull request by kaptron**
merging into #638 since it extends the new preference checkbox setup

### CODE REVIEW

**Comment by kaptron** [comment]
build is failing because the Geocoder is down, causing NRHP to not show up when it's expected

**Comment by chrisdolendo** [comment]
👍

**Comment by creativecoder** [comment]
Note, didn't see this before merging #638 to master, so changed pull request to merge to master, then reset branch to master and cherry picked e4b3ac19c7324d42b9ffe7945b80ea5eeb885342, the one unique commit on this branch.

**Comment by creativecoder** [comment]
Re-triggering CI

**Pull request merged**
